### ISSUE TITLE
Toughts on grammar and semantics

### ISSUE THREAD

**Issue by TangoMan75** [yoanbernabeu/Airtable-Client-Bundle#17]
Hi Yoan, 👋

I was looking at your videos 👍 and I thought I could help on your Airtable project with a couple suggestions.

### 💡 1. Rename `findTheLatest()` to `findLast()`

🔥 Affected files:
- 📝 README (line 72)
- 📂 src/AirtableClient (line 80)
- 📂 src/AirtableClientInterface (line 48)
- ✅ tests/AirtableClientTest lines(211-248)

Though not grammatically incorrect per se, usage of superlative `Latest` and article `The` makes me cringe 😬 a little. I suppose native english speaker would simply use `findLast()`. For example if we would need to retrieve the first item in Airtable we would not name the method `findTheFirst()` we would simply name it `findFirst()` IMHO.

### 💡 2. Rename `addOneRecord()` to `addRecord()`, or `add()`

🔥 Affected files:
- 📝 README (line 74)
- 📂 src/AirtableClient (line 113)
- 📂 src/AirtableClientInterface (line 57)
- ✅ tests/AirtableClientTest lines(312-363)

Do you plan to develop a `addMultipleRecords()` method at some point in the future ? If not, maybe `addRecord()` would be just as good from a semantics point of view then... Or just `add()`. I like to keep method names short and simple.

### 💡 3. Rename `findOneById()` to `find()`

🔥 Affected files:
- 📝 README (line 65)
- 📂 src/AirtableClient (line 65)
- 📂 src/AirtableClientInterface (line 39)
- ✅ tests/AirtableClientTest lines(267-293)

With `Doctrine` we would just use `find()` method to query an item by id from the database, I suggest to use the same convention.

---

Tell me what you think about it, and I will work on a PR to fix this.

Hope that helps, peace ✌

**Comment by liorchamla** [comment]
I love it, would you file a PR for those changes ? If you don't plan to propose, I could implement this when I have time, let me know :)

**Comment by TangoMan75** [comment]
Hi @liorchamla, 👋
it is not a lot of work at all, I can have a PR ready quite soon.
