### ISSUE TITLE
About branch naming

### ISSUE THREAD

**Issue by Spomky** [yoanbernabeu/Airtable-Client-Bundle#18]
Hi,

I noted this repository has only one branch named `main`. 
As the project evolves, at some point you will undoubtedly need to manage versions. 
What about starting with a branch `1.0` and push tags when the bundle is stable?
Next versions will be merge in this branch (bug fixes), a branch 1.x (e.g. new features) and a branch 2.x for major changes. 
WDYT?

**Comment by TangoMan75** [comment]
Hi @Spomky 👋
What's wrong with standard [gitflow](https://www.atlassian.com/fr/git/tutorials/comparing-workflows/gitflow-workflow) ?

**Comment by yoanbernabeu** [comment]
You're right, we need to set up version control.

We will follow the [best practices of a Symfony Bundle](https://symfony.com/doc/current/bundles/best_practices.html#versioning) using [SemVer](https://semver.org/).

[Packagist](https://packagist.org/about#managing-package-versions) also recommends the use of SemVer.
Packagist offers the following approach:

> New versions of your package are automatically fetched from tags you create in your VCS repository.
> The easiest way to manage versioning is to just omit the version field from the composer.json file. The version numbers will then be parsed from the tag and branch names.

However, I would like to keep the process simple.
Can't we just use tags?

**Comment by Spomky** [comment]
> What's wrong with standard gitflow ?

Nothing wrong with gitflow.

> However, I would like to keep the process simple.
> Can't we just use tags?

Yes actually this is exactly what you should do.
You will put tags like `1.0.0` on commits. The question is about branches.
Symfony best practices are very clever on that point. Have a look on [their branch organization](https://github.com/symfony/symfony/branches). This way you can work on any versions an easy way. The process is very similar to the one you use. The only difference is that instead of creating new working branches from the `main` one, you start from a `x.y` one.

**Comment by yoanbernabeu** [comment]
My proposal: As long as we are in the initial version (tag 0. *. *), I suggest that we do not use branches.
When version 1.0.0 is released, we will be implementing the branch naming system.

Is it okay for you ?

**Comment by Spomky** [comment]
That's just naming suggestion.
If it is 👌 for you, it's 👌 for me as well!
Proposal accepted ✔.
